name: 'build'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to publish'     
        required: true
  #push:
  #  branches:
  #  - master
  #pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: nya1
          password: ${{ secrets.PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/nya1/zebrahook:${{ github.event.inputs.version }},ghcr.io/nya1/zebrahook:latest
