name: 'build'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to publish'     
        required: true
  #push:
  #  branches:
  #  - master
  #pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      -
        name: Login to docker registry
        uses: docker/login-action@v2
        with:
          username: nya1
          password: ${{ secrets.PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: nya1/zebrahook:${{ github.event.inputs.version }},nya1/zebrahook:latest
